export default {
  NOMINAL_SET : 'BALANCE_NOMINAL_SET',
  NOMINAL_RESET : 'BALANCE_NOMINAL_RESET',
  PAYMENT_METHOD_FETCH: 'BALANCE_PAYMENT_METHOD_FETCH',
  PAYMENT_METHOD_FETCHED: 'BALANCE_PAYMENT_METHOD_FETCHED',
  PAYMENT_METHOD_FETCH_CANCELED: 'BALANCE_PAYMENT_METHOD_FETCH_CANCELED',
  PAYMENT_METHOD_SET : 'BALANCE_PAYMENT_METHOD_SET',
  PAYMENT_METHOD_RESET : 'BALANCE_PAYMENT_METHOD_RESET',

  PAYMENT_SUBMIT:    'BALANCE_PAYMENT_SUBMIT',
  PAYMENT_SUBMITTED: 'BALANCE_PAYMENT_SUBMITTED',
  PAYMENT_CANCELED:  'BALANCE_PAYMENT_CANCELED',
  PAYMENT_RESET:     'BALANCE_PAYMENT_RESET',

  PAYMENT_INFO_VISIBILITY : 'BALANCE_PAYMENT_INFO_VISIBILITY',

  PAYMENT_TRANSACTION_FETCH :     'BALANCE_PAYMENT_TRANSACTION_FETCH',
  PAYMENT_TRANSACTION_FETCHED :   'BALANCE_PAYMENT_TRANSACTION_FETCHED',
  PAYMENT_TRANSACTION_CANCELED :  'BALANCE_PAYMENT_TRANSACTION_CANCELED',
  PAYMENT_TRANSACTION_RESET:      'BALANCE_PAYMENT_TRANSACTION_RESET',

  TOP_UP_HISTORY_FETCH: 'BALANCE_TOP_UP_HISTORY_FETCH',
  TOP_UP_HISTORY_FETCHED: 'BALANCE_TOP_UP_HISTORY_FETCHED',
  TOP_UP_HISTORY_RESET: 'BALANCE_TOP_UP_HISTORY_RESET',
  TOP_UP_HISTORY_CANCELED: 'BALANCE_TOP_UP_HISTORY_CANCELED'
};