const PREFIX = "BALANCE_MUTATION";

export default {

  SCROLL_PAGINATION_FETCH: `${PREFIX}_SCROLL_PAGINATION_FETCH`,
  SCROLL_PAGINATION_FETCHED: `${PREFIX}_SCROLL_PAGINATION_FETCHED`,
  SCROLL_PAGINATION_RESET: `${PREFIX}_SCROLL_PAGINATION_RESET`,

  NUMBER_PAGINATION_FETCH: `${PREFIX}_NUMBER_PAGINATION_FETCH`,
  NUMBER_PAGINATION_FETCHED: `${PREFIX}_NUMBER_PAGINATION_FETCHED`,
  NUMBER_PAGINATION_CANCELED: `${PREFIX}_NUMBER_PAGINATION_CANCELED`

}