const prefix = 'BALANCE_TRANSFER_';

export default {

  MEMBER_INFO_FETCH: `${prefix}MEMBER_INFO_FETCH`,
  MEMBER_INFO_FETCHED: `${prefix}MEMBER_INFO_FETCHED`,
  MEMBER_INFO_CANCELED: `${prefix}MEMBER_INFO_CANCELED`,
  MEMBER_INFO_RESET: `${prefix}MEMBER_INFO_RESET`

}