export default {
  INIT: 'APP_INIT',
  SSE_AGEN_INIT: 'APP_SSE_AGEN_INIT',
  SSE_EVENT_LOGIN: 'APP_SSE_EVENT_LOGIN',
  LOGOUT: 'APP_LOGOUT',
  STATES_RESET: 'APP_STATES_RESET',
  WINDOW_RESIZE: 'APP_WINDOW_RESIZE'
};