export default {

  INIT: 'APP_INIT',

  HOST_CHECK: 'APP_HOST_CHECK',
  HOST_CHECKED: 'APP_HOST_CHECKED',

  SSE_AGEN_INITIALIZING: 'APP_SSE_AGEN_INITIALIZING',
  SSE_AGEN_INITIALIZED: 'APP_SSE_AGEN_INITIALIZED',
  SSE_EVENT_LOGIN: 'APP_SSE_EVENT_LOGIN',

  ROUTER_CHANGE: 'APP_ROUTER_CHANGE',

  LOGOUT: 'APP_LOGOUT',
  LOGGING_OUT: 'APP_LOGGING_OUT',
  LOGGED_OUT: 'APP_LOGGED_OUT',
  LOGOUT_CANCELED: 'APP_LOGOUT_CANCELED',

  SWITCH_PLATFORM :'APP_SWITCH_PLATFORM',

  STATES_RESET: 'APP_STATES_RESET',

  WINDOW_RESIZE: 'APP_WINDOW_RESIZE',

  LOADING_INDICATOR_SHOW: 'APP_LOADING_INDICATOR_SHOW',
  LOADING_INDICATOR_HIDE: 'APP_LOADING_INDICATOR_HIDE',

  DIALOG_PROFILE_PHOTO_OPEN : 'APP_DIALOG_PROFILE_PHOTO_OPEN',
  DIALOG_PROFILE_PHOTO_CLOSE : 'APP_DIALOG_PROFILE_PHOTO_CLOSE',

  DIALOG_ADDRESS_INPUT_OPEN : 'APP_DIALOG_ADDRESS_INPUT_OPEN',
  DIALOG_ADDRESS_INPUT_CLOSE : 'APP_DIALOG_ADDRESS_INPUT_CLOSE',

  DIALOG_EMAIL_INPUT_OPEN : 'APP_DIALOG_EMAIL_INPUT_OPEN',
  DIALOG_EMAIL_INPUT_CLOSE : 'APP_DIALOG_EMAIL_INPUT_CLOSE',

  DIALOG_NOTICE_OPEN : 'APP_DIALOG_NOTICE_OPEN',
  DIALOG_NOTICE_CLOSE : 'APP_DIALOG_NOTICE_CLOSE'
};
