export default {
  PROFILE_GET : 'USER_PROFILE_GET',
  PROFILE_UPDATE: 'USER_PROFILE_UPDATE',

  PASSWORD_UPDATE_SUBMIT : 'USER_PASSWORD_UPDATE_SUBMIT',
  PASSWORD_UPDATE_SUBMITTED : 'USER_PASSWORD_UPDATE_SUBMITTED',
  PASSWORD_UPDATE_CANCELED : 'USER_PASSWORD_UPDATE_CANCELED',

  PASSWORD_UPDATE_OTP_SUBMIT : 'USER_PASSWORD_UPDATE_OTP_REQUEST',
  PASSWORD_UPDATE_OTP_SUBMITTED : 'USER_PASSWORD_UPDATE_OTP_SUBMITTED',
  PASSWORD_UPDATE_OTP_CANCELED : 'USER_PASSWORD_UPDATE_OTP_CANCELED',

  PASSWORD_UPDATE_DIALOG_OPEN: 'USER_PASSWORD_UPDATE_DIALOG_OPEN',
  PASSWORD_UPDATE_DIALOG_CLOSE: 'USER_PASSWORD_UPDATE_DIALOG_CLOSE'

};